In [18]:
import numpy as np
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])


In [4]:
#get specific value
a[1,-2]

13

In [5]:
#get a specific row works without specifying the row with colon(:)
a[0,]

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
#doesn't work without specifying the row or leaving it with colon(:)
a[:,2]

array([ 3, 10])

In [9]:
a[0,1:6:2]

array([2, 4, 6])

In [19]:
#modifying an entry
a[1,-2] = 15
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 15 14]]


In [20]:
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 15 14]]


In [21]:
 b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [22]:
# Get specific element (work outside in)
b[0,1,1]

4

In [24]:
# replace 
b[:,1,:] = [[9,9,],[8,8]]