In [13]:
import numpy as np
a = np.array([1,2,3], dtype = 'int16' )
a

array([1, 2, 3], dtype=int16)

In [14]:
print(a)

[1 2 3]


In [15]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [16]:
#get dimensions
a.ndim

1

In [17]:
b.ndim

2

In [18]:
#shape
a.shape


(3,)

In [19]:
b.shape

(2, 3)

In [20]:
#type
a.dtype

dtype('int16')

In [22]:
#size
a.itemsize

2

In [23]:
a.size

3

In [25]:
a.nbytes

6

In [26]:
b.itemsize

4