**All Zeros's**

In [2]:
import numpy as np
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

**All Ones**

In [6]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [7]:
np.full((2,2), 34)

array([[34, 34],
       [34, 34]])

In [8]:
 a = ([[1,2,3,4,4],[1,2,3,4,5]])
np.full_like(a,4)

array([[4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4]])

In [10]:
np.random.rand(2,3,4)


array([[[0.70078969, 0.02153408, 0.57859957, 0.98150306],
        [0.38134504, 0.030393  , 0.59707469, 0.03186887],
        [0.78338051, 0.37947355, 0.90795203, 0.50229778]],

       [[0.43592255, 0.77101691, 0.37127622, 0.28358652],
        [0.79679379, 0.09827497, 0.78569091, 0.66186478],
        [0.8710538 , 0.54813824, 0.8275695 , 0.82592631]]])

In [20]:
np.random.randint(-5, 9, size = (3,3))

array([[ 4, -4, -5],
       [ 4,  7, -5],
       [ 8,  3,  4]])

In [21]:
#identity matrix
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [27]:
#repeating an array
ar = np.array([[1,2,3]])
r1 = np.repeat(ar,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [47]:
#Exercise from tutorial
ed = np.ones((5,5))
ed[1:-1,1:-1] = 0
ed[2,2] = 9
print(ed)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays #####


In [48]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)
print(b)

[100   2   3]
[100   2   3]


In [52]:
c = np.array([1,2,3])
d = c.copy()
d[0] = 100
print(c)
print(d)

[1 2 3]
[100   2   3]
