In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
a + 2

array([3, 4, 5, 6])

In [4]:
a -2

array([-1,  0,  1,  2])

In [5]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [6]:
a * 2

array([2, 4, 6, 8])

In [10]:
b = np.array([0,1,2,1,])
a + b

array([5, 7, 9, 9])

In [11]:
#take the sin
np.sin(a)

array([-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825])

In [12]:
np.cos(a)

array([ 0.28366219,  0.96017029,  0.75390225, -0.14550003])

##### Linear Algebra #####

In [16]:
a = np.ones([2,3])
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
b = np.full((3,2), 2)
b

array([[2, 2],
       [2, 2],
       [2, 2]])

In [18]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [19]:
c = np.identity(3)
c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
np.linalg.det(c)

1.0

In [ ]:
#more linear algebra functions from th pdf