# Reorganizing Arrays #


In [1]:
import numpy as np

In [9]:
bef = np.array([[1,2,3,4],[5,6,7,8]])
bef.shape

(2, 4)

In [12]:
after = bef.reshape((4,2))
after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [14]:
af = after.reshape((2,2,2))
af

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [17]:
#vertical stacking vectors
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [19]:
np.vstack([a,b,a,b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.hstack([a,])