In [2]:
from numpy import *
a = zeros(3)
a

array([0., 0., 0.])

In [4]:
z = linspace(2, 10, 6)
z

array([ 2. ,  3.6,  5.2,  6.8,  8.4, 10. ])

In [6]:
t = array([2, 4, 5])
t

array([2, 4, 5])

In [7]:
type(t)

numpy.ndarray

In [8]:
b = [[1,2,3],[4,5,6]]
b

[[1, 2, 3], [4, 5, 6]]

In [9]:
x = array(b)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
d = array([1,2,3,4,5,6])
e = array([10,20,30,40,50])
d


array([10, 20, 30, 40, 50])

In [13]:
d > 3

array([False, False, False,  True,  True,  True])

In [15]:
d[d>=3]

array([3, 4, 5, 6])

In [16]:
d * 10

array([10, 20, 30, 40, 50, 60])

In [23]:
e

array([10, 20, 30, 40, 50])

In [24]:
d + e

ValueError: operands could not be broadcast together with shapes (6,) (5,) 

In [25]:
d @ e

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 5 is different from 6)